spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mariadb://localhost:3306/house
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: message_group
      isolation-level: read_committed
      enable-auto-commit: true